name: CI/CD Nexus

on: [pull_request, push]

jobs:
  continuous-integration:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      
      - name: "Copiar arquivos para a VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.HOST}} 
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          port: ${{secrets.PORT}}
          source: "."
          target: "/home/eduardo/dinodex"